name: Publish to NuGet

on:
  push:
    tags:
      - 'releases/*'

env:
  CONFIGURATION: Release
jobs:
  build:
    # Sets permissions of the GITHUB_TOKEN to allow release creating
    permissions:
      contents: write
    environment:
      name: nuget
    runs-on: ubuntu-latest

    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        ports:
          - 8081:8081
          - 8080:8080
          - 1234:1234
        env:
          PROTOCOL: https
    steps:
      - uses: actions/checkout@v6
      - name: Setup necessary dotnet SDKs
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
          dotnet-version: |
            10.x
            8.x

      - name: Setup Azure Cosmos DB Emulator
        uses: ./.github/actions/setup-cosmos-emulator

      - name: Publish to NuGet
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FAKE_DETAILED_ERRORS: true
          ENABLE_COVERAGE: false # AltCover doesn't work with Release builds, reports lower coverage than actual
        run: |
          chmod +x ./build.sh
          ./build.sh Publish
